import { Download, FileText } from 'lucide-react'
import { useAuth } from '@/auth/AuthProvider'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { DefinitionRow, PageHeader } from '@/components/ui/patterns'
import { lagosFullDateTime, naira } from '@/lib/format'
import { downloadCsv, percent } from '@/lib/utils'
import { store } from '@/db/store'
import { writeAudit } from '@/server/audit'
import { toast } from 'sonner'
import { useProgramme } from './institution-data'

/** Monthly statement. Aggregated only; a named-passenger export is not offered to institutions. */
export function ProgrammeReports() {
  const { actor } = useAuth()
  const p = useProgramme()
  const month = p.today.slice(0, 7)

  function exportStatement() {
    const rows: (string | number | null)[][] = [
      ['Metric', 'Value'],
      ['Organisation', p.organization?.name ?? ''],
      ['Period', month],
      ['Policy', p.policy ? `${p.policy.name} v${p.policy.version}` : 'None'],
      ['Eligible staff', p.eligibleStaff],
      ['Registered riders', p.registered],
      ['Adoption %', percent(p.registered, p.eligibleStaff)],
      ['Active riders this month', p.activeRiders],
      ['Sponsored trips', p.tripsThisMonth],
      ['Gross transport value ₦', p.grossTransportValue],
      ['Staff contribution ₦', p.passengerContribution],
      ['Institution subsidy recognised ₦', p.subsidyRecognized],
      ['Institution subsidy reserved ₦', p.subsidyReserved],
      ['Released on cancellation ₦', p.subsidyReleased],
      ['Programme ceiling ₦', p.policy?.programme_budget ?? null],
      ['Budget consumed ₦', p.policy?.budget_consumed ?? null],
      ['Rejected subsidy claims', p.rejections],
      [],
      ['Corridor', 'Sponsored trips', 'Subsidy ₦'],
      ...p.corridors.map((c) => [`${c.code} ${c.name}`, c.trips, c.subsidy]),
      [],
      ['Report', 'Institutional monthly statement'],
      ['Generated', lagosFullDateTime(new Date().toISOString())],
      ['Generated by', actor.name],
      ['Filters', `sponsor = ${p.organization?.code}; month = ${month}`],
      ['Definitions', 'Subsidy is reserved at booking, recognised at boarding, released on cancellation. Aggregated totals only.'],
    ]
    downloadCsv(`damov-${p.organization?.code ?? 'institution'}-statement-${month}.csv`, rows)
    store.transact((draft) => writeAudit(draft, { actor_id: actor.id, actor_name: actor.name, action: 'report.exported', entity_type: 'report', entity_id: 'institutional-statement', summary: `Institutional statement for ${p.organization?.short_name} · ${month}`, severity: 'notice' }))
    toast.success('Statement exported')
  }

  return (
    <div className="space-y-5">
      <PageHeader title="Reports" description="Downloadable monthly statement with definitions and provenance. PDF statements arrive with the next milestone." actions={<Button onClick={exportStatement}><Download className="size-4" /> Export statement (CSV)</Button>} />
      <Card>
        <CardHeader><CardTitle className="flex items-center gap-2"><FileText className="size-4 text-primary" /> Statement preview · {month}</CardTitle></CardHeader>
        <CardContent>
          <dl className="divide-y divide-border rounded-lg border border-border px-3">
            <DefinitionRow term="Eligible staff">{p.eligibleStaff}</DefinitionRow>
            <DefinitionRow term="Registered riders">{p.registered} ({percent(p.registered, p.eligibleStaff)}%)</DefinitionRow>
            <DefinitionRow term="Active riders">{p.activeRiders}</DefinitionRow>
            <DefinitionRow term="Sponsored trips">{p.tripsThisMonth}</DefinitionRow>
            <DefinitionRow term="Gross transport value">{naira(p.grossTransportValue)}</DefinitionRow>
            <DefinitionRow term="Staff contribution">{naira(p.passengerContribution)}</DefinitionRow>
            <DefinitionRow term="Institution subsidy recognised">{naira(p.subsidyRecognized)}</DefinitionRow>
            <DefinitionRow term="Subsidy reserved (not yet boarded)">{naira(p.subsidyReserved)}</DefinitionRow>
            <DefinitionRow term="Remaining budget">{naira(Math.max(0, (p.policy?.programme_budget ?? 0) - (p.policy?.budget_consumed ?? 0)))}</DefinitionRow>
            <DefinitionRow term="Rejected claims">{p.rejections}</DefinitionRow>
          </dl>
        </CardContent>
      </Card>
    </div>
  )
}
